/**
 * Round 53b — `NarrationEngine.fnv1a` test vectors.
 *
 * These tests lock the FNV-1a 32-bit hash function output so a
 * future change to the hash formula (or the wrong constants)
 * fails loudly. The pinned values were generated by the canonical
 * Rust implementation at
 * `cocos4-rust/src/agi_minigame/narration.rs::fnv1a` and verified
 * byte-for-byte against an independent Python implementation:
 *
 *     def fnv1a(s):
 *         h = 0x811c9dc5
 *         for c in s:
 *             h ^= ord(c)
 *             h = (h * 0x01000193) & 0xFFFFFFFF
 *         return h
 *
 * The test file is intentionally a separate file (not appended to
 * `NarrationEngine.test.ts`) so the locked-down test surface is
 * obvious — anyone touching this file is either accepting the
 * hash formula change or rolling back to the previous one.
 *
 * **What this does NOT lock**: the specific pool entry picked
 * for a given (id, branch) — round 30/33's variety tests in
 * `NarrationEngine.test.ts` (≥3/4/3 unique over 30 ids) still
 * run and verify the hash is well-distributed.
 */

import { NarrationEngine } from '../narration/NarrationEngine';
import { fnv1a32 } from '../ai/Mood4thSentence';

describe('NarrationEngine — round 53b fnv1a hash function', () => {
    // Round 70 — the FNV-1a 32-bit hash moved out of
    // `NarrationEngine` (where it was a private method) into the
    // new `Mood4thSentence` module as a stand-alone exported
    // function. The pinned test vectors below still apply — same
    // constants, same byte-for-byte match against the Rust
    // implementation in `cocos4-rust/src/agi_minigame/narration.rs`.
    const fnv1a = fnv1a32;

    test('empty_string_returns_FNV_offset_basis', () => {
        // FNV-1a 32-bit offset basis = 2166136261 = 0x811c9dc5.
        expect(fnv1a('')).toBe(0x811c9dc5);
    });

    test('ascii_blueprint_id_dim_42', () => {
        // Pinned from Rust `fnv1a("dim_42")` output:
        //   2166136261 ^ ord('d') = 0x811c9dc5 ^ 0x64 = 0x811c9da1
        //   ... chain through 6 bytes ...
        //   final = 0x05798420 = 91849760
        expect(fnv1a('dim_42')).toBe(0x05798420);
    });

    test('ascii_id_with_hyphen_r30-fear-0', () => {
        // Pinned from Rust output. mod 4 = 2 → idx 2 in the fear
        // pool (round 30: 4-entry pool).
        expect(fnv1a('r30-fear-0')).toBe(0xa7b40dce);
    });

    test('ascii_id_with_underscore_r30_friendly_15', () => {
        // Pinned from Rust output. mod 4 = 3, mod 5 = 2.
        expect(fnv1a('r30_friendly_15')).toBe(0x071d3003);
    });

    test('ascii_id_r30-hostile-7', () => {
        // Pinned from Rust output. mod 4 = 1 → idx 1 in the
        // hostile pool (round 30: 4-entry pool).
        expect(fnv1a('r30-hostile-7')).toBe(0x1fd04dc9);
    });

    test('hash_mod_pool_fear_size_4', () => {
        // 4-entry fear pool: idx ∈ [0, 3].
        const h = fnv1a('dim_42');
        expect(h % 4).toBe(0);
        expect(h % 4).toBeGreaterThanOrEqual(0);
        expect(h % 4).toBeLessThan(4);
    });

    test('hash_mod_pool_loved_size_5', () => {
        // 5-entry loved (friendly) pool: idx ∈ [0, 4].
        const h = fnv1a('r30-friendly-3');
        expect(h % 5).toBe(2);
        expect(h % 5).toBeGreaterThanOrEqual(0);
        expect(h % 5).toBeLessThan(5);
    });

    test('hash_mod_pool_hostile_size_4', () => {
        // 4-entry hostile pool: idx ∈ [0, 3].
        const h = fnv1a('r30-hostile-7');
        expect(h % 4).toBe(1);
        expect(h % 4).toBeGreaterThanOrEqual(0);
        expect(h % 4).toBeLessThan(4);
    });

    test('hash_is_u32_shaped_for_modular_safety', () => {
        // The `>>> 0` at the end of `fnv1a` returns a non-negative
        // integer in the u32 range. This catches the regression
        // where someone drops the `>>> 0` and the result becomes
        // negative on inputs whose hash exceeds 2^31.
        const h = fnv1a('dim_42');
        expect(h).toBeGreaterThanOrEqual(0);
        expect(h).toBeLessThanOrEqual(0xFFFFFFFF);
    });

    test('identical_inputs_produce_identical_hash', () => {
        // Determinism sanity check: same string in, same u32 out.
        const a = fnv1a('r30-stable');
        const b = fnv1a('r30-stable');
        expect(a).toBe(b);
    });

    test('hash_does_not_collide_across_distinct_ids', () => {
        // 10 distinct ids → 10 distinct u32 values (probabilistically
        // very high; FNV-1a is a good hash, not perfect, but for
        // 10 ASCII strings of length 6-15, collisions are astronomically
        // rare). This catches a bug where the hash collapses to a
        // constant (e.g. someone resets `h` inside the loop).
        const seen = new Set<number>();
        for (let i = 0; i < 10; i++) {
            seen.add(fnv1a(`distinct-id-${i}`));
        }
        expect(seen.size).toBe(10);
    });
});
