import type { DimensionBlueprint } from './AiEngine';

import { TowerModule } from './modules/TowerModule';
import { Match3Module } from './modules/Match3Module';
import { ParkourModule } from './modules/ParkourModule';
import { ShooterModule } from './modules/ShooterModule';
import { RuleCompiler } from './RuleSystem';
import type { CompiledRuleSet } from './RuleSystem';

export interface ModuleConfig {
    difficulty: number;
    customParams: Record<string, any>;
}

export interface GameplayModule {
    id: string;
    name: string;
    config: ModuleConfig;
    assets: string[]; // 独立的美术资源列表
    
    load(): Promise<void>;
    update(dt: number): void;
    unload(): void;
    
    // 供统一经济或成长系统调用的结算接口
    getScore(): number;
}

export class GameplayManager {
    private activeModules: Map<string, GameplayModule> = new Map();
    private activeRules: CompiledRuleSet | null = null;

    // 根据 AI 给出的组合，动态无缝加载玩法模块
    async loadCombination(blueprint: DimensionBlueprint): Promise<void> {
        console.log(`[GameplayManager] Loading dimension: ${blueprint.name}`);
        console.log(`[GameplayManager] AI selected modules: ${blueprint.modules.join(', ')}`);
        this.activeRules = RuleCompiler.compile(blueprint);
        console.log(`[GameplayManager] Active AGI rules: ${this.activeRules.summary.join(' | ')}`);
        
        // 卸载当前所有模块
        this.unloadAll();

        // 模拟按需动态加载（AI 决定）
        for (const moduleId of blueprint.modules) {
            const module = this.createModuleInstance(moduleId);
            if (module) {
                module.config = RuleCompiler.applyToModuleConfig(
                    moduleId,
                    { ...module.config, difficulty: blueprint.difficulty },
                    this.activeRules
                );
                await module.load();
                this.activeModules.set(moduleId, module);
                console.log(`[GameplayManager] Module loaded: ${moduleId}`);
            }
        }
    }

    private createModuleInstance(moduleId: string): GameplayModule | null {
        // 使用工厂模式实例化注册的具体模块
        switch (moduleId) {
            case 'tower_defense':
                return new TowerModule();
            case 'match3':
                return new Match3Module();
            case 'parkour':
                return new ParkourModule();
            case 'shooter':
                return new ShooterModule();
            case 'synthesis':
                return this.createGeneratedModule(moduleId, '3D 合成模块');
            case 'card':
                return this.createGeneratedModule(moduleId, '3D 卡牌模块');
            case 'turn_combat':
                return this.createGeneratedModule(moduleId, '3D 回合战斗模块');
            case 'puzzle':
                return this.createGeneratedModule(moduleId, '3D 解谜模块');
            default:
                // Fallback for unknown modules generated by AI
                console.warn(`[GameplayManager] Unknown module ID: ${moduleId}, creating fallback mock module.`);
                return this.createGeneratedModule(moduleId, `Mock ${moduleId.toUpperCase()}`);
        }
    }

    private createGeneratedModule(moduleId: string, name: string): GameplayModule {
        let score = 0;
        return {
            id: moduleId,
            name,
            config: { difficulty: 1, customParams: { generated: true } },
            assets: [],
            load: async () => { console.log(`[GameplayManager] Loaded generated module ${moduleId}`) },
            update: (dt: number) => { score += dt * 2 * (this.activeRules?.moduleEffects[moduleId]?.scoreMultiplier ?? 1); },
            unload: () => { },
            getScore: () => Math.floor(score),
        };
    }

    toggleModule(moduleId: string, enable: boolean): void {
        if (enable && !this.activeModules.has(moduleId)) {
            const mod = this.createModuleInstance(moduleId);
            if (mod) {
                mod.load().then(() => this.activeModules.set(moduleId, mod));
            }
        } else if (!enable && this.activeModules.has(moduleId)) {
            const mod = this.activeModules.get(moduleId);
            mod?.unload();
            this.activeModules.delete(moduleId);
        }
    }

    update(dt: number): void {
        for (const module of this.activeModules.values()) {
            module.update(dt);
        }
    }

    unloadAll(): void {
        for (const module of this.activeModules.values()) {
            module.unload();
        }
        this.activeModules.clear();
    }

    getActiveRuleSummary(): string[] {
        return this.activeRules?.summary ?? [];
    }

    getActiveRules(): CompiledRuleSet | null {
        return this.activeRules;
    }

    getTotalScore(): number {
        let total = 0;
        for (const module of this.activeModules.values()) {
            total += module.getScore();
        }
        return Math.floor(total);
    }
}
